# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matthew/lib/jewel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matthew/lib/jewel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthew/lib/jewel/CMakeFiles /home/matthew/lib/jewel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthew/lib/jewel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named jewel

# Build rule for target.
jewel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jewel
.PHONY : jewel

# fast build rule for target.
jewel/fast:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/build
.PHONY : jewel/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

arithmetic_exceptions.o: arithmetic_exceptions.cpp.o
.PHONY : arithmetic_exceptions.o

# target to build an object file
arithmetic_exceptions.cpp.o:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/arithmetic_exceptions.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/arithmetic_exceptions.cpp.o
.PHONY : arithmetic_exceptions.cpp.o

arithmetic_exceptions.i: arithmetic_exceptions.cpp.i
.PHONY : arithmetic_exceptions.i

# target to preprocess a source file
arithmetic_exceptions.cpp.i:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/arithmetic_exceptions.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/arithmetic_exceptions.cpp.i
.PHONY : arithmetic_exceptions.cpp.i

arithmetic_exceptions.s: arithmetic_exceptions.cpp.s
.PHONY : arithmetic_exceptions.s

# target to generate assembly for a file
arithmetic_exceptions.cpp.s:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/arithmetic_exceptions.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/arithmetic_exceptions.cpp.s
.PHONY : arithmetic_exceptions.cpp.s

checked_arithmetic.o: checked_arithmetic.cpp.o
.PHONY : checked_arithmetic.o

# target to build an object file
checked_arithmetic.cpp.o:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/checked_arithmetic.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/checked_arithmetic.cpp.o
.PHONY : checked_arithmetic.cpp.o

checked_arithmetic.i: checked_arithmetic.cpp.i
.PHONY : checked_arithmetic.i

# target to preprocess a source file
checked_arithmetic.cpp.i:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/checked_arithmetic.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/checked_arithmetic.cpp.i
.PHONY : checked_arithmetic.cpp.i

checked_arithmetic.s: checked_arithmetic.cpp.s
.PHONY : checked_arithmetic.s

# target to generate assembly for a file
checked_arithmetic.cpp.s:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/checked_arithmetic.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/checked_arithmetic.cpp.s
.PHONY : checked_arithmetic.cpp.s

checked_arithmetic_tests.o: checked_arithmetic_tests.cpp.o
.PHONY : checked_arithmetic_tests.o

# target to build an object file
checked_arithmetic_tests.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/checked_arithmetic_tests.cpp.o
.PHONY : checked_arithmetic_tests.cpp.o

checked_arithmetic_tests.i: checked_arithmetic_tests.cpp.i
.PHONY : checked_arithmetic_tests.i

# target to preprocess a source file
checked_arithmetic_tests.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/checked_arithmetic_tests.cpp.i
.PHONY : checked_arithmetic_tests.cpp.i

checked_arithmetic_tests.s: checked_arithmetic_tests.cpp.s
.PHONY : checked_arithmetic_tests.s

# target to generate assembly for a file
checked_arithmetic_tests.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/checked_arithmetic_tests.cpp.s
.PHONY : checked_arithmetic_tests.cpp.s

decimal.o: decimal.cpp.o
.PHONY : decimal.o

# target to build an object file
decimal.cpp.o:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/decimal.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/decimal.cpp.o
.PHONY : decimal.cpp.o

decimal.i: decimal.cpp.i
.PHONY : decimal.i

# target to preprocess a source file
decimal.cpp.i:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/decimal.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/decimal.cpp.i
.PHONY : decimal.cpp.i

decimal.s: decimal.cpp.s
.PHONY : decimal.s

# target to generate assembly for a file
decimal.cpp.s:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/decimal.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/decimal.cpp.s
.PHONY : decimal.cpp.s

decimal_tests.o: decimal_tests.cpp.o
.PHONY : decimal_tests.o

# target to build an object file
decimal_tests.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/decimal_tests.cpp.o
.PHONY : decimal_tests.cpp.o

decimal_tests.i: decimal_tests.cpp.i
.PHONY : decimal_tests.i

# target to preprocess a source file
decimal_tests.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/decimal_tests.cpp.i
.PHONY : decimal_tests.cpp.i

decimal_tests.s: decimal_tests.cpp.s
.PHONY : decimal_tests.s

# target to generate assembly for a file
decimal_tests.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/decimal_tests.cpp.s
.PHONY : decimal_tests.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

num_digits.o: num_digits.cpp.o
.PHONY : num_digits.o

# target to build an object file
num_digits.cpp.o:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/num_digits.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/num_digits.cpp.o
.PHONY : num_digits.cpp.o

num_digits.i: num_digits.cpp.i
.PHONY : num_digits.i

# target to preprocess a source file
num_digits.cpp.i:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/num_digits.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/num_digits.cpp.i
.PHONY : num_digits.cpp.i

num_digits.s: num_digits.cpp.s
.PHONY : num_digits.s

# target to generate assembly for a file
num_digits.cpp.s:
	$(MAKE) -f CMakeFiles/jewel.dir/build.make CMakeFiles/jewel.dir/num_digits.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/num_digits.cpp.s
.PHONY : num_digits.cpp.s

num_digits_tests.o: num_digits_tests.cpp.o
.PHONY : num_digits_tests.o

# target to build an object file
num_digits_tests.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/num_digits_tests.cpp.o
.PHONY : num_digits_tests.cpp.o

num_digits_tests.i: num_digits_tests.cpp.i
.PHONY : num_digits_tests.i

# target to preprocess a source file
num_digits_tests.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/num_digits_tests.cpp.i
.PHONY : num_digits_tests.cpp.i

num_digits_tests.s: num_digits_tests.cpp.s
.PHONY : num_digits_tests.s

# target to generate assembly for a file
num_digits_tests.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/num_digits_tests.cpp.s
.PHONY : num_digits_tests.cpp.s

power_vector_tests.o: power_vector_tests.cpp.o
.PHONY : power_vector_tests.o

# target to build an object file
power_vector_tests.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/power_vector_tests.cpp.o
.PHONY : power_vector_tests.cpp.o

power_vector_tests.i: power_vector_tests.cpp.i
.PHONY : power_vector_tests.i

# target to preprocess a source file
power_vector_tests.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/power_vector_tests.cpp.i
.PHONY : power_vector_tests.cpp.i

power_vector_tests.s: power_vector_tests.cpp.s
.PHONY : power_vector_tests.s

# target to generate assembly for a file
power_vector_tests.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/power_vector_tests.cpp.s
.PHONY : power_vector_tests.cpp.s

stopwatch_tests.o: stopwatch_tests.cpp.o
.PHONY : stopwatch_tests.o

# target to build an object file
stopwatch_tests.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stopwatch_tests.cpp.o
.PHONY : stopwatch_tests.cpp.o

stopwatch_tests.i: stopwatch_tests.cpp.i
.PHONY : stopwatch_tests.i

# target to preprocess a source file
stopwatch_tests.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stopwatch_tests.cpp.i
.PHONY : stopwatch_tests.cpp.i

stopwatch_tests.s: stopwatch_tests.cpp.s
.PHONY : stopwatch_tests.s

# target to generate assembly for a file
stopwatch_tests.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stopwatch_tests.cpp.s
.PHONY : stopwatch_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... doc"
	@echo "... edit_cache"
	@echo "... jewel"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... arithmetic_exceptions.o"
	@echo "... arithmetic_exceptions.i"
	@echo "... arithmetic_exceptions.s"
	@echo "... checked_arithmetic.o"
	@echo "... checked_arithmetic.i"
	@echo "... checked_arithmetic.s"
	@echo "... checked_arithmetic_tests.o"
	@echo "... checked_arithmetic_tests.i"
	@echo "... checked_arithmetic_tests.s"
	@echo "... decimal.o"
	@echo "... decimal.i"
	@echo "... decimal.s"
	@echo "... decimal_tests.o"
	@echo "... decimal_tests.i"
	@echo "... decimal_tests.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... num_digits.o"
	@echo "... num_digits.i"
	@echo "... num_digits.s"
	@echo "... num_digits_tests.o"
	@echo "... num_digits_tests.i"
	@echo "... num_digits_tests.s"
	@echo "... power_vector_tests.o"
	@echo "... power_vector_tests.i"
	@echo "... power_vector_tests.s"
	@echo "... stopwatch_tests.o"
	@echo "... stopwatch_tests.i"
	@echo "... stopwatch_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

